stages:
  - build
  - buildImage
  - publish

build:
  stage: build
  image: golang:1.13-alpine
  script:
    - GOOS=darwin go build -o macos/aws-secretsmanager-proxy main.go
    - GOOS=linux go build -o linux/aws-secretsmanager-proxy main.go
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    paths:
      - macos
      - linux

buildImage:
  stage: buildImage
  image: docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

publishImage:
  stage: publish
  image: docker:dind
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - tags
